---
dependency:
  name: galaxy
driver:
  name: openstack
lint:
  name: yamllint
platforms:
  - name: u1610
    image: Ubuntu-16.04
    flavor: m1-medium
  - name: centos7
    image: centos7
    flavor: m1-medium
provisioner:
  name: ansible
  lint:
    name: ansible-lint
scenario:
  name: openstack-unict
verifier:
  name: testinfra
  lint:
    name: flake8
